INSERT INTO Genre (name) VALUES
    ('Fiction'),
    ('Non-fiction'),
    ('Mystery'),
    ('Thriller'),
    ('Romance'),
    ('Science Fiction'),
    ('Fantasy'),
    ('Horror'),
    ('Biography'),
    ('Autobiography'),
    ('History'),
    ('Self-help'),
    ('Poetry'),
    ('Drama'),
    ('Comedy');